# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b2da03239d803a3e22c8352feb9da9d"
name = "custom-purchase-logic"
handle = "custom-purchase-logic"
application_url = "https://see-wash-angeles-bikes.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://see-wash-angeles-bikes.trycloudflare.com/auth/callback",
  "https://see-wash-angeles-bikes.trycloudflare.com/auth/shopify/callback",
  "https://see-wash-angeles-bikes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
